export { default as Home } from "./home";
export { default as Browse } from "./browse";
export { default as Signin } from "./signin";
export { default as Signup } from "./signup";
export { default as Movies } from "./movies";
export { default as Series } from "./series";
export { default as Movie } from "./movie";
export { default as Seasons } from "./seasons";
export { default as Seasonepisode } from "./seasonepisode";
